version: '3'
services:
  axonserver:
    image: axoniq/axonserver:4.0.3
    ports:
    - 8024:8024
    - 8124:8124
    environment:
    - AXONSERVER_HOSTNAME=axonserver
    volumes:
    - axonserver-vol:/opt/axonserver/data
  demo-api-mongodb:
    image: mongo:3.6.9
    command: mongod
    ports:
    - 27017:27017
    volumes:
    - demo-api-mongodb-vol:/data/db
 
volumes:
  demo-api-mongodb-vol: 
  axonserver-vol: 
